/**
 * Positional weights for the opponent, one set per mode.
 *
 * These are *data*, not judgement: `tools/train.mjs` fits them by self-play
 * and rewrites the block between the markers below. The BASELINE values are
 * the hand-tuned ones training starts from, kept so the fitted weights can be
 * measured against something.
 */
export const BASELINE = {
  classic: { w1: 2, w2: 26, w3: 340, w4: 7000, defence: 1, sweep: 0, deny: 0, fence: 0 },
  torque: { w1: 2, w2: 26, w3: 340, w4: 7000, defence: 1, sweep: 0, deny: 0, fence: 0 },
  encircle: { w1: 2, w2: 26, w3: 340, w4: 7000, defence: 1, sweep: 1500, deny: 1, fence: 0 },
};

/** Fields the trainer may move, and the range it may move them in. */
export const TUNABLE = {
  w1: [0.2, 40], w2: [2, 400], w3: [30, 4000], w4: [500, 60000],
  defence: [0.2, 2.5], sweep: [0, 40000], deny: [0, 3], fence: [0, 4000],
};

/* LEARNED-BEGIN — generated by tools/train.mjs, do not edit by hand */
export const LEARNED = {
  classic: { w1: 1.2011, w2: 26.22, w3: 1361.1, w4: 2839.9, defence: 1.0072, sweep: 0.0000010583, deny: 0.29798, fence: 0.0000016701 },
  torque: { w1: 2, w2: 26, w3: 340, w4: 7000, defence: 1, sweep: 0, deny: 0, fence: 0 },
  encircle: { w1: 1.8148, w2: 41.677, w3: 262.17, w4: 10672, defence: 0.91411, sweep: 1767.6, deny: 1.1404, fence: 0.0000015116 },
};
/* LEARNED-END */

/**
 * How deep Hard searches in each mode; depth 0 means it plays the best static
 * move. Set by measurement in tools/evaluate.mjs, not by taste.
 */
export const SEARCH = {
  classic: { depth: 0, width: 8 },
  torque: { depth: 3, width: 8 },
  encircle: { depth: 3, width: 8 },
};

export function weightsFor(mode) {
  // Fall back per mode, not wholesale: a partial training run must not leave
  // one mode borrowing another's weights.
  return (LEARNED && LEARNED[mode]) || BASELINE[mode] || BASELINE.classic;
}
